production:
  app:
    name: the-mondobot
    git_branch: master
  config_vars:
    - BUILDPACK_URL: https://github.com/heroku/heroku-buildpack-ruby.git
    - SLACK_API_TOKEN: <%= ENV['SLACK_API_TOKEN'] %>
    - LOG_LEVEL: debug
  addons: []
  resources:
    web:
      count: 1
      type: Free
